version: "3"
services:
  nginx:
    image: nginx:1.19.10-alpine
    ports: 
      - "3000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - nest-issue-tracker
  postgres:
    image: postgres:12.6-alpine
    restart: always
    volumes:
      - pg-data:/var/lib/postgresql/data
    env_file: ./.env
  nest-issue-tracker:
    build: .
    env_file: ./.env
    depends_on: 
      - postgres

volumes:
  pg-data:
